name: my_first_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  file_picker:
  cupertino_icons:
  http:
  mysql1:
  flutter_bcrypt:
  shared_preferences:
  font_awesome_flutter: ^10.1.0
  table_calendar:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  launcher_name: ^1.0.2

# dart run launcher_name:main
launcher_name:
  default: "Pawssible Solutions"

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/  # Ensure your logo is located here
